name: Build-Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y musl-tools libssl-dev pkg-config

      - name: Install rustup target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Set environment variables
        run: |
          export OPENSSL_DIR=/usr
          export PKG_CONFIG_PATH=$OPENSSL_DIR/lib/pkgconfig
          export PKG_CONFIG_SYSROOT_DIR=/

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Archive artifacts
        run: |
          cp target/x86_64-unknown-linux-musl/release/rbackup* ./
          tar -czvf rbackup.tar.gz ./rbackup* config.toml.template
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latest-package
          path: rbackup.tar.gz
