name: Build-Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y musl-tools musl-dev pkg-config

      - name: Download and install OpenSSL
        run: |
          curl -O https://www.openssl.org/source/openssl-1.1.1u.tar.gz
          tar -xzf openssl-1.1.1u.tar.gz
          cd openssl-1.1.1u
          ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl no-shared
          make
          sudo make install
        env:
          OPENSSL_VERSION: 1.1.1u

      - name: Build
        env:
          OPENSSL_STATIC: 1
          OPENSSL_DIR: /usr/local/openssl
          OPENSSL_LIB_DIR: /usr/local/openssl/lib
          OPENSSL_INCLUDE_DIR: /usr/local/openssl/include
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Archive artifacts
        run: |
          cp target/x86_64-unknown-linux-musl/release/rbackup* ./
          tar -czvf rbackup.tar.gz ./rbackup* config.toml.template

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: latest-package
          path: rbackup.tar.gz
