name: Build-Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install Visual C++ Redistributable
        run: |
          curl -L -o vc_redist.x64.exe https://aka.ms/vs/17/release/vc_redist.x64.exe
          Start-Process -FilePath .\vc_redist.x64.exe -ArgumentList '/quiet', '/install' -NoNewWindow -Wait

      - name: Build
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Archive artifacts
        run: |
          Copy-Item -Path .\target\x86_64-pc-windows-msvc\release\rbackup.exe -Destination .\
          Compress-Archive -Path .\rbackup.exe, .\config.toml -DestinationPath rbackup.zip
        if: success()

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: rbackup.zip
